### ISSUE TITLE
Error when working with mongodb inside docker container using pymongo

### ISSUE THREAD

**Issue by Abhijit-2592** [docker-library/mongo#253] opened 2018-03-12 08:17 UTC
I am running Mongodb(3.6.3) in a server, inside a docker container (data_mongo). I have another container with anaconda and pymongo installed which is linked to the above mongo container (--link data_mongo:mongo). I use pymongo(3.6.1) to interact with mongodb. I remote access the database and the server from my system. I connect to MongoDB via pymongo using `client = MongoClient("mongo",27017)`. When I run :

```
db.command({'collMod':str(collectionName),
'validator':{},
'validationLevel':'off',
'validationAction':'warn'}
)
```
It runs without errors. But when I open Compass GUI and connect it to the database and run the above command I get the following error:

> pymongo.errors.OperationFailure: no such command: 'validator', bad cmd: '{ validator: {}, collMod: "TEST_SCHEMA_COLLECTION", validationAction: "warn", validationLevel: "off", lsid:
> 
> Unknown macro: { id}
> , $readPreference:
> 
> Unknown macro: { mode}
> , $db: "TEST_SCHEMA_DB" }'

**PS**:
I installed MongoDB, pymongo, compass in my local system and tried the same code, it worked without errors. Thus this happens only when I am remotely accessing the mongodb within a docker container in server

**Update**: Repeatedly running the same command again and again also creates the same error. First time it runs without any errors but in the it creates the above error in the consequent runs

**Comment by yosifkit** [comment] 2018-03-13 21:12
I am unable to reproduce with the mongo shell. Perhaps pymongo is adding more to the command than is necessary? Does `db.getCollectionInfos()` show the correct output?

```console
$ docker run -d --name mongo mongo:3.6.3
...
$ docker run -it --rm --link mongo mongo:3.6.3 mongo mongo/mongo
MongoDB shell version v3.6.3
connecting to: mongodb://mongo:27017/mongo
MongoDB server version: 3.6.3
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2018-03-13T21:00:06.651+0000 I STORAGE  [main] In File::open(), ::open for '/home/mongodb/.mongorc.js' failed with No such file or directory
Server has startup warnings: 
2018-03-13T20:56:41.901+0000 I STORAGE  [initandlisten] 
2018-03-13T20:56:41.901+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-03-13T20:56:41.901+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-03-13T20:56:42.303+0000 I CONTROL  [initandlisten] 
2018-03-13T20:56:42.303+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-03-13T20:56:42.303+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-03-13T20:56:42.303+0000 I CONTROL  [initandlisten] 
> db.runCommand({collMod: test, validator: {}, validationLevel: 'off', validationAction: 'warn'})
2018-03-13T21:01:40.497+0000 E QUERY    [thread1] ReferenceError: test is not defined :
@(shell):1:16
> db.runCommand({collMod: 'test', validator: {}, validationLevel: 'off', validationAction: 'warn'})
{
	"ok" : 0,
	"errmsg" : "ns does not exist",
	"code" : 26,
	"codeName" : "NamespaceNotFound"
}
> db.test.insert({})
WriteResult({ "nInserted" : 1 })
> db.runCommand({collMod: 'test', validator: {}, validationLevel: 'off', validationAction: 'warn'})
{ "ok" : 1 }
> db.runCommand({collMod: 'test', validator: {}, validationLevel: 'off', validationAction: 'warn'})
{ "ok" : 1 }
> db.runCommand({collMod: 'test', validator: {}, validationLevel: 'off', validationAction: 'warn'})
{ "ok" : 1 }
> db.runCommand({collMod: 'test', validator: {}, validationLevel: 'off', validationAction: 'warn'})
> db.getCollectionInfos()
[
	{
		"name" : "test",
		"type" : "collection",
		"options" : {
			"validationLevel" : "off",
			"validationAction" : "warn"
		},
		"info" : {
			"readOnly" : false,
			"uuid" : UUID("801dc694-387b-47de-95a0-8ff85d39b2ec")
		},
		"idIndex" : {
			"v" : 2,
			"key" : {
				"_id" : 1
			},
			"name" : "_id_",
			"ns" : "mongo.test"
		}
	}
]
> 
bye
```

**Comment by MaBeuLux88** [comment] 2018-04-17 13:29
By the way, Docker deprecated `--link` a long time ago already. Prefer using `docker network` now.
CF : [Legacy containers link](https://docs.docker.com/network/links/)

**Comment by tianon** [comment] 2018-04-23 23:11
Closing, since this appears to be an issue with PyMongo, not the image. :+1:

**Closed by tianon** 2018-04-23 23:11 UTC
