### ISSUE TITLE
Got '"docker-entrypoint.sh": executable file not found in $PATH' while run an container

### ISSUE THREAD

**Issue by jodotlearn** [docker-library/mongo#248] opened 2018-02-20 05:44 UTC
I used the following command to build an image
`docker build -t mango:3.7 .`

and run a container from the above image:
`docker run -d -p 27017:27017 -v $PWD/db:/data/db mango:3.7`

then i got the error as follow:
"docker-entrypoint.sh": executable file not found in $PATH

My docker engine is in Mac OS.
It worked after I add the following command in Dockerfile to give executable permission to the docker-entrypoint.sh.

`RUN chmod +x /usr/local/bin/docker-entrypoint.sh`

**Comment by yosifkit** [comment] 2018-02-20 21:23
Duplicate of https://github.com/docker-library/mongo/pull/208.

**Closed by yosifkit** 2018-02-20 21:23 UTC
