### ISSUE TITLE
mongo 3.0 exits with code 139

### ISSUE THREAD

**Issue by leotrt** [docker-library/mongo#269] opened 2018-05-07 07:22 UTC
Hi,

After updating the kernel ( 4.16.6-1-ARCH ), I am not able to run mongo:3.0 containers anymore, they all exit with code 139. I don't even have logs of the container (ie `docker log my_mongo_container`).

Any idea on what may cause this ? 

Thanks a lot,
Leo

**Comment by wglambert** [comment] 2018-05-07 17:05
Are other containers/images affected, have you done a re-pull of the affected images

Also try `docker events` in another terminal and then run the image

**Comment by leotrt** [comment] 2018-05-09 06:46
Hi wglambert,

Yes, I tried to re-pull the images, but it hasn't changed a thing.
I have a mongo:latest image that is working fine, and a homemade Dockerfile based on debian that is also working fine.

Here are the events triggered a simple `docker run` of a mongo 3.0.15 container:
`docker run --name some-mongo -d mongo:3.0.15`
2018-05-09T08:40:27.595747698+02:00 image pull mongo:3.0.15 (name=mongo)
2018-05-09T08:40:38.220899758+02:00 container create d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809 (image=mongo:3.0.15, name=some-mongo)
2018-05-09T08:40:38.243063507+02:00 network connect 620fac644c818057e1314e41f99d07ccf492e4db4cef9edd3cb35a820f273972 (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, name=bridge, type=bridge)
2018-05-09T08:40:38.250935763+02:00 volume mount c368ceba87e6c738f007e807c63a95e6778e394e6d4d1ff2a531e35ae5e439d3 (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, destination=/data/configdb, driver=local, propagation=, read/write=true)
2018-05-09T08:40:38.251067071+02:00 volume mount b9151c5d09fbe89b17017904d33977cf44e06d3e9697d3b55028d5b04c67aadf (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, destination=/data/db, driver=local, propagation=, read/write=true)
2018-05-09T08:40:38.664328882+02:00 container start d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809 (image=mongo:3.0.15, name=some-mongo)
2018-05-09T08:40:39.079726509+02:00 container die d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809 (exitCode=139, image=mongo:3.0.15, name=some-mongo)
2018-05-09T08:40:39.282205096+02:00 network disconnect 620fac644c818057e1314e41f99d07ccf492e4db4cef9edd3cb35a820f273972 (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, name=bridge, type=bridge)
2018-05-09T08:40:39.377011440+02:00 volume unmount c368ceba87e6c738f007e807c63a95e6778e394e6d4d1ff2a531e35ae5e439d3 (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, driver=local)
2018-05-09T08:40:39.377041811+02:00 volume unmount b9151c5d09fbe89b17017904d33977cf44e06d3e9697d3b55028d5b04c67aadf (container=d518d042365027bf1192b49aae05c185c1df63c15aff14e73baa16851ae47809, driver=local)

**Comment by yosifkit** [comment] 2018-05-09 17:12
I doubt it is kernel related, but I'll try to test this on a newer kernel once I reboot (currently on `4.16.2`, moving to `4.16.7`).

On a related note, 3.0 was end of life in February 2018 and will no longer be a tag we support: https://github.com/docker-library/mongo/pull/272.

**Comment by yosifkit** [comment] 2018-05-09 18:05
Couldn't reproduce, worked fine on kernel `4.16.7`.

**Comment by wglambert** [comment] 2018-05-15 17:38
Since this doesn't seem to be an image issue but an environmental one I'm going to close

If you believe this to be in error then let me know and I'll re-open it

**Closed by wglambert** 2018-05-15 17:38 UTC
