### ISSUE TITLE
 Docker on Windows: Operation not permitted

### ISSUE THREAD

**Issue by levarato** [docker-library/mongo#107] opened 2016-08-04 16:24 UTC
Hi,
I'm not able to run on Windows Mongo , with shared drives enabled. The following simple command will fail: docker run -v c:/data/prova:/data/db mongo

This is my docker version:
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

```

This is the log:
```
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=4435f9551aa2
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] db version v3.2.8
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] git version: ed70e33130c977bda0024c125b56d159573dbaf0
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] modules: none
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] build environment:
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten]     distmod: debian71
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten]     distarch: x86_64
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2016-08-04T16:20:33.421+0000 I CONTROL  [initandlisten] options: {}
2016-08-04T16:20:33.430+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=sn
appy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2016-08-04T16:20:33.448+0000 E STORAGE  [initandlisten] WiredTiger (1) [1470327633:448337][1:0x7f11809dfc80], connection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2016-08-04T16:20:33.451+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted
2016-08-04T16:20:33.451+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 1: Operation not permitted, terminating
2016-08-04T16:20:33.452+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
```

The folder C:\data\prova on windows creates these files: 
* mongod.lock
* WiredTiger
* WiredTiger.lock
* WiredTiger.wt

**Comment by gladmo** [comment] 2016-09-08 08:21
+1
![image](https://cloud.githubusercontent.com/assets/18359830/18342198/235ecc78-75e0-11e6-8679-bcd616eb0b2d.png)

**Comment by yosifkit** [comment] 2016-09-08 18:19
Duplicate of #85 and #74. Specifically https://github.com/docker-library/mongo/issues/74#issuecomment-175855893.  If you have Windows 10 Pro, you can run the `windowsservercore` variant: https://github.com/docker-library/docs/tree/master/mongo#mongowindowsservercore.

**Closed by yosifkit** 2016-09-08 18:19 UTC

**Comment by jeremyml** [comment] 2017-08-03 15:21
I like @yosifkit 's [solution ](https://github.com/docker-library/mongo/issues/74#issuecomment-172675750) to simply mount it on the virtual machine.  A major reason I use docker is to develop on an environment more like production.  I develop on windows and push to linux production anyway - so why not cut windows out of the db?

**Comment by hinell** [comment] 2017-08-26 20:03
Strangely it works if I mount volume into ``/data/`` folder ...

**Comment by yosifkit** [comment] 2017-08-28 22:51
@hinell, if you mount `/data/` as the volume it will be basically empty from the host perspective.  It will only contain two folders (`db` and `configdb`) and they will both be empty.  They are still volumes from Docker's perspective so they will still get automatic volumes created that will be mounted on those folders.

**Comment by hinell** [comment] 2017-08-29 20:43
@yosifkit Well, recently I discovered it doesn't work. If I specify ``--dbpath`` to ``/data/`` I get the same error.
