### ISSUE TITLE
Support for arm32v7

### ISSUE THREAD

**Issue by Serkan-devel** [docker-library/mongo#209] opened 2017-10-23 13:19 UTC
Is there any? I want to run a local pump.io instace on a raspberry pi.

**Comment by tianon** [comment] 2017-10-23 15:51
See the discussion over on https://github.com/docker-library/mongo/issues/196.  I doubt upstream is going to officially support arm32 since MongoDB on 32bit platforms is limited to 4GB IIRC (and they don't actively support i386 anymore, for example).

**Comment by tianon** [comment] 2017-12-20 00:47
Closing as a duplicate of #196 (so we can keep the "multi-architecture" discussion in one place).

**Closed by tianon** 2017-12-20 00:47 UTC
