### ISSUE TITLE
Declared volumes make deploying image as "pre-built" db extremely difficult

### ISSUE THREAD

**Issue by mshafer-NI** [docker-library/mongo#613] opened 2023-03-15 15:54 UTC
## High level
I'm trying to build a db into an image to deploy (read-only) in a k8s cluster. I need to be able to build it one environment and deploy in a completely different one.

## Desired behavior

Ability to (within my Dockerfile):
* start `FROM mongo`, 
* launch the db in background (can use tmux for this)
* run script to populate db
* stop db
* commit as image

## Blockers currently (/ other solutions if they would work)
* Because these images declare volumes for `/data/db`, 
  * Docker generates an ephemeral volume whenever a descendant image is launched. 
  * Docker appears to not allow a client Dockerfile to "reset" volumes (like we can entrypoint and cmd), 
* Nor have I been able to figure out how to get mongod to store the initial db in a different folder.

**Comment by tianon** [comment] 2023-03-15 23:17
The easiest workaround is to pass `--dbpath` to a different path, which all our scripts (and `mongod` itself) will honor:

https://github.com/docker-library/mongo/blob/2a7ebf4d0dd1499409dc209443c86846f0c96510/docker-entrypoint.sh#L224-L228

(Otherwise, this is a duplicate of https://github.com/docker-library/mongo/issues/306)

**Closed by tianon** 2023-03-15 23:17 UTC
