### ISSUE TITLE
Mongo 5.0.6 doesn't populate initial user

### ISSUE THREAD

**Issue by BrianAllred** [docker-library/mongo#524] opened 2022-03-02 17:38 UTC
Not sure if this is a bug in the Docker image or upstream, but I'll start here.

Since the update to Mongo 5.0.6, my `init-mongo.sh` script doesn't populate my initial non-root user like it used to. Script below, logs attached.

`init-mongo.sh`
```
#!/bin/sh

mongosh -- "$MONGO_INITDB_DATABASE" <<EOF
    var rootUser = '$MONGO_INITDB_ROOT_USERNAME';
    var rootPassword = '$MONGO_INITDB_ROOT_PASSWORD';
    var admin = db.getSiblingDB('admin');
    admin.auth(rootUser, rootPassword);

    var user = '$MONGO_INITDB_USERNAME';
    var passwd = '$MONGO_INITDB_PASSWORD';
    db.createUser({user: user, pwd: passwd, roles: ["readWrite"]});
EOF
```

`docker-compose.yml`
```
version: "3"

services:

  mongo:
    image: mongo
    restart: always
    command: --port 27020
    ports:
      - 27020:27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: nowplaying
      MONGO_INITDB_PASSWORD: example
      MONGO_INITDB_DATABASE: spotify
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27020/
    networks:
      - mongo-network

networks:
  mongo-network:


```

[mongo-v5.0.6-logs.txt](https://github.com/docker-library/mongo/files/8171691/mongo-v5.0.6-logs.txt)
[mongo-v5.0.5-logs.txt](https://github.com/docker-library/mongo/files/8171692/mongo-v5.0.5-logs.txt)

**Comment by tianon** [comment] 2022-03-02 18:05
I'm not sure what's changed, but in the logs you shared in the place where v5.0.5 appears to run the mongosh code successfully, v5.0.6 includes the following error message:

```
AssertionError: You must pass either an "anonymousId" or a "userId".
```

This sounds like it's probably related? :grimacing:

**Comment by BrianAllred** [comment] 2022-03-02 18:12
I saw that, too. Looks like the 5.0.6 image includes an upgrade from `mongosh` 1.1.7 to 1.2.2. Can't seem to find anything related in the mongosh changelogs, though.

**Comment by wglambert** [comment] 2022-03-02 18:28
Yeah I wasn't able to reproduce the error on `5.0.6`

<details>
<summary> docker logs 5.0.6</summary>

```console
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-mongo.sh
Warning: Could not access file: EACCES: permission denied, mkdir '/home/mongodb'
Current Mongosh Log ID: 621fb186880592c8755d6406
Connecting to:          mongodb://127.0.0.1:27017/spotify?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.1.9
{"t":{"$date":"2022-03-02T18:03:50.530+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45322","uuid":"f5bc8850-7de2-4baa-a7f1-ce7928cf171b","connectionId":3,"connectionCount":1}}
{"t":{"$date":"2022-03-02T18:03:50.535+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"127.0.0.1:45322","client":"conn3","doc":{"driver":{"name":"nodejs|mongosh","version":"4.3.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)","version":"4.3.0|1.1.9","application":{"name":"mongosh 1.1.9"}}}}
{"t":{"$date":"2022-03-02T18:03:50.550+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45324","uuid":"e75a84d0-04f0-46ba-92ff-d997b588a541","connectionId":4,"connectionCount":2}}
{"t":{"$date":"2022-03-02T18:03:50.551+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"127.0.0.1:45324","client":"conn4","doc":{"driver":{"name":"nodejs|mongosh","version":"4.3.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)","version":"4.3.0|1.1.9","application":{"name":"mongosh 1.1.9"}}}}
{"t":{"$date":"2022-03-02T18:03:50.556+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45326","uuid":"195237d5-66d1-4929-a984-f4a87dde891f","connectionId":5,"connectionCount":3}}
{"t":{"$date":"2022-03-02T18:03:50.557+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"127.0.0.1:45326","client":"conn5","doc":{"driver":{"name":"nodejs|mongosh","version":"4.3.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)","version":"4.3.0|1.1.9","application":{"name":"mongosh 1.1.9"}}}}
Using MongoDB:          5.0.6
Using Mongosh:          1.1.9

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting:
   2022-03-02T18:03:47.582+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2022-03-02T18:03:48.162+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2022-03-02T18:03:48.162+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
------


Error: Could not open history file.
REPL session history will not be persisted.
spotify>
spotify>
spotify>
spotify> {"t":{"$date":"2022-03-02T18:03:51.967+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45346","uuid":"69e64076-f198-4c9b-abb8-f3625382547c","connectionId":6,"connectionCount":4}}
{"t":{"$date":"2022-03-02T18:03:51.988+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"127.0.0.1:45346","client":"conn6","doc":{"driver":{"name":"nodejs|mongosh","version":"4.3.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)","version":"4.3.0|1.1.9","application":{"name":"mongosh 1.1.9"}}}}
{"t":{"$date":"2022-03-02T18:03:51.993+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:45348","uuid":"0915c089-7500-4999-8a39-3da9a8ef5498","connectionId":7,"connectionCount":5}}
{"t":{"$date":"2022-03-02T18:03:51.994+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn7","msg":"client metadata","attr":{"remote":"127.0.0.1:45348","client":"conn7","doc":{"driver":{"name":"nodejs|mongosh","version":"4.3.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)","version":"4.3.0|1.1.9","application":{"name":"mongosh 1.1.9"}}}}
{"t":{"$date":"2022-03-02T18:03:52.022+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn7","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"127.0.0.1:45348","extraInfo":{}}}
{"t":{"$date":"2022-03-02T18:03:52.028+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn3","msg":"Interrupted operation as its client disconnected","attr":{"opId":80}}
{"t":{"$date":"2022-03-02T18:03:52.030+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn3","msg":"Connection ended","attr":{"remote":"127.0.0.1:45322","uuid":"f5bc8850-7de2-4baa-a7f1-ce7928cf171b","connectionId":3,"connectionCount":4}}
{"t":{"$date":"2022-03-02T18:03:52.032+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn4","msg":"Connection ended","attr":{"remote":"127.0.0.1:45324","uuid":"e75a84d0-04f0-46ba-92ff-d997b588a541","connectionId":4,"connectionCount":3}}
{"t":{"$date":"2022-03-02T18:03:52.033+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn5","msg":"Connection ended","attr":{"remote":"127.0.0.1:45326","uuid":"195237d5-66d1-4929-a984-f4a87dde891f","connectionId":5,"connectionCount":2}}
{ ok: 1 }
spotify>
spotify>
spotify>
spotify> { ok: 1 }
spotify> {"t":{"$date":"2022-03-02T18:03:52.274+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"127.0.0.1:45346","uuid":"69e64076-f198-4c9b-abb8-f3625382547c","connectionId":6,"connectionCount":1}}
{"t":{"$date":"2022-03-02T18:03:52.275+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7","msg":"Connection ended","attr":{"remote":"127.0.0.1:45348","uuid":"0915c089-7500-4999-8a39-3da9a8ef5498","connectionId":7,"connectionCount":0}}
```
</details>

<details>
<summary> docker logs 5.0.5 </summary>

```console
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-mongo.sh
{"t":{"$date":"2022-03-02T18:14:00.045+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"127.0.0.1:56366","uuid":"1f28f795-076a-4176-8b94-d9b278b6e576","connectionId":2,"connectionCount":0}}
Warning: Could not access file: EACCES: permission denied, mkdir '/home/mongodb'
Current Mongosh Log ID: 621fb3e9134930463cb9eb1f
Connecting to:          mongodb://127.0.0.1:27017/spotify?directConnection=true&serverSelectionTimeoutMS=2000
{"t":{"$date":"2022-03-02T18:14:01.421+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:56398","uuid":"8ff870a9-917f-48aa-982a-a79784b4b87f","connectionId":3,"connectionCount":1}}
{"t":{"$date":"2022-03-02T18:14:01.426+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"127.0.0.1:56398","client":"conn3","doc":{"driver":{"name":"nodejs","version":"4.2.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)|Node.js v14.18.0, LE (unified)","application":{"name":"mongosh 1.1.7"}}}}
{"t":{"$date":"2022-03-02T18:14:01.439+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:56400","uuid":"d9507d74-45ec-4e81-b8ee-f75355fa5e07","connectionId":4,"connectionCount":2}}
{"t":{"$date":"2022-03-02T18:14:01.442+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"127.0.0.1:56400","client":"conn4","doc":{"driver":{"name":"nodejs","version":"4.2.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)|Node.js v14.18.0, LE (unified)","application":{"name":"mongosh 1.1.7"}}}}
{"t":{"$date":"2022-03-02T18:14:01.449+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:56402","uuid":"51bb052e-d563-4322-bfad-37bcf7950872","connectionId":5,"connectionCount":3}}
{"t":{"$date":"2022-03-02T18:14:01.451+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"127.0.0.1:56402","client":"conn5","doc":{"driver":{"name":"nodejs","version":"4.2.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)|Node.js v14.18.0, LE (unified)","application":{"name":"mongosh 1.1.7"}}}}
Using MongoDB:          5.0.5
Using Mongosh:          1.1.7

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting:
   2022-03-02T18:13:58.995+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2022-03-02T18:13:59.639+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2022-03-02T18:13:59.639+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
------


Error: Could not open history file.
REPL session history will not be persisted.
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
spotify>
spotify>
spotify>
spotify> {"t":{"$date":"2022-03-02T18:14:02.827+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:56428","uuid":"56a805eb-878b-4c84-8fca-99ee3bf47cbc","connectionId":6,"connectionCount":4}}
{"t":{"$date":"2022-03-02T18:14:02.831+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"127.0.0.1:56428","client":"conn6","doc":{"driver":{"name":"nodejs","version":"4.2.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)|Node.js v14.18.0, LE (unified)","application":{"name":"mongosh 1.1.7"}}}}
{"t":{"$date":"2022-03-02T18:14:02.833+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:56430","uuid":"b00a0b89-ce91-474b-a040-7dff0a67f00a","connectionId":7,"connectionCount":5}}
{"t":{"$date":"2022-03-02T18:14:02.836+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn7","msg":"client metadata","attr":{"remote":"127.0.0.1:56430","client":"conn7","doc":{"driver":{"name":"nodejs","version":"4.2.2"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"Node.js v14.18.0, LE (unified)|Node.js v14.18.0, LE (unified)","application":{"name":"mongosh 1.1.7"}}}}
{"t":{"$date":"2022-03-02T18:14:02.853+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn7","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"127.0.0.1:56430","extraInfo":{}}}
{"t":{"$date":"2022-03-02T18:14:02.857+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn3","msg":"Interrupted operation as its client disconnected","attr":{"opId":73}}
{"t":{"$date":"2022-03-02T18:14:02.858+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn3","msg":"Connection ended","attr":{"remote":"127.0.0.1:56398","uuid":"8ff870a9-917f-48aa-982a-a79784b4b87f","connectionId":3,"connectionCount":4}}
{"t":{"$date":"2022-03-02T18:14:02.861+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn5","msg":"Connection ended","attr":{"remote":"127.0.0.1:56402","uuid":"51bb052e-d563-4322-bfad-37bcf7950872","connectionId":5,"connectionCount":3}}
{"t":{"$date":"2022-03-02T18:14:02.861+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn4","msg":"Connection ended","attr":{"remote":"127.0.0.1:56400","uuid":"d9507d74-45ec-4e81-b8ee-f75355fa5e07","connectionId":4,"connectionCount":2}}
{ ok: 1 }
spotify>
spotify>
spotify>
spotify> { ok: 1 }
spotify> {"t":{"$date":"2022-03-02T18:14:03.161+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"127.0.0.1:56428","uuid":"56a805eb-878b-4c84-8fca-99ee3bf47cbc","connectionId":6,"connectionCount":1}}
{"t":{"$date":"2022-03-02T18:14:03.161+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7","msg":"Connection ended","attr":{"remote":"127.0.0.1:56430","uuid":"b00a0b89-ce91-474b-a040-7dff0a67f00a","connectionId":7,"connectionCount":0}}
```

</details>

```console
$ docker exec -it mongo_mongo_1 mongo -u nowplaying -p example --authenticationDatabase spotify --port 27020
MongoDB shell version v5.0.6
connecting to: mongodb://127.0.0.1:27020/?authSource=spotify&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("52c5784d-bafb-4562-b93c-ed108d0610c6") }
MongoDB server version: 5.0.6
================
Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.
For installation instructions, see
https://docs.mongodb.com/mongodb-shell/install/
================
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        https://docs.mongodb.com/
Questions? Try the MongoDB Developer Community Forums
        https://community.mongodb.com
>
```

It is `MongoDB shell version v5.0.6`

**Comment by BrianAllred** [comment] 2022-03-02 18:34
Now I think it most likely is related to the mongosh version bump. Your Mongo 5.0.6 ran with mongosh 1.1.9 instead of 1.2.2 like mine.

**Comment by tianon** [comment] 2022-05-09 22:26
Closing as this isn't something we're going to fix in the image -- I would suggest following up with the maintainers of `mongosh`/MongoDB itself to determine whether this is an expected change. :+1:

**Closed by tianon** 2022-05-09 22:26 UTC
Labels: question

**Comment by yosifkit** [comment] 2022-05-20 22:24
After some testing, `mongosh` is storing **required** data in `$HOME/.mongodb/mongosh/config` that looks to be related to  "anonymous usage data" of `mongosh` that might be eventually sent to MongoDB and that is where the `AssertionError: You must pass either an "anonymousId" or a "userId".` is coming from. Even if opted out, it still will fail without a writable `HOME`. The `.mongodb` directory can be deleted, but I think any settings like the telemetry opt-out would be lost.

(Discovered after reading a little into the changes in https://github.com/mongodb-js/mongosh/pull/1229)

```console
$ # after connecting to mongod with mongosh while running as `root`
root@5a6683ec104d:/# ls -la /root/.mongodb/mongosh/
total 28
drwx------ 3 root root 4096 May 19 00:31 .
drwx------ 3 root root 4096 May 19 00:28 ..
-rw------- 1 root root 5703 May 19 00:31 62858f46d31c51c7e3b1bff0_log
-rw------- 1 root root  141 May 19 00:31 config
-rw------- 1 root root   18 May 19 00:31 mongosh_repl_history
drwxr-xr-x 2 root root 4096 May 19 00:28 snippets
$ cat /root/.mongodb/mongosh/config 
{"userId":"62859030ac18a01331c6812a","telemetryAnonymousId":"62859030ac18a01331c6812a","enableTelemetry":true,"disableGreetingMessage":true}
```
I am working on a fix to add a `HOME` value for the `mongodb` user we create and to ensure that a docker run with any `--user` will also work (assuming that you provide a `/data/db` the user can write to).

**Comment by ferrao** [comment] 2022-05-23 10:52
> I'm not sure what's changed, but in the logs you shared in the place where v5.0.5 appears to run the mongosh code successfully, v5.0.6 includes the following error message:
> 
> ```
> AssertionError: You must pass either an "anonymousId" or a "userId".
> ```
> 
> This sounds like it's probably related? grimacing

This issue is caused by missing `mongodb` user home directory, I have mentioned this in #537
