### ISSUE TITLE
Errors getting started

### ISSUE THREAD

**Issue by KevinBurton** [docker-library/mongo#232] opened 2018-01-04 21:49 UTC
I issue the command

`docker run --name mymongo -v //c/mongodb:/data/db -d mongo`

and the container immediately exits.

When I look at the logs (docker logs mymongo) I get:

```
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=
0e6b202f1271
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] db version v3.6.1
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] git version: 025d4f4fe61efd1fb6f0005be20cb45a004093d1
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-01-04T21:32:20.159+0000 I CONTROL  [initandlisten] modules: none
2018-01-04T21:32:20.160+0000 I CONTROL  [initandlisten] build environment:
2018-01-04T21:32:20.160+0000 I CONTROL  [initandlisten]     distmod: debian81
2018-01-04T21:32:20.160+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-01-04T21:32:20.160+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-01-04T21:32:20.160+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
2018-01-04T21:32:20.187+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=478M,session_max=20000
,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,
compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-01-04T21:32:20.301+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1515101540:300975][1:0x7f7cd61cda00], conn
ection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2018-01-04T21:32:20.303+0000 E -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage
/wiredtiger/wiredtiger_kv_engine.cpp 413
2018-01-04T21:32:20.305+0000 I STORAGE  [initandlisten] exception in initAndListen: Location28595: 1: Operation not perm
itted, terminating
2018-01-04T21:32:20.305+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2018-01-04T21:32:20.305+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2018-01-04T21:32:20.305+0000 I CONTROL  [initandlisten] now exiting
2018-01-04T21:32:20.305+0000 I CONTROL  [initandlisten] shutting down with code:100
```

How do I determine which operation is not permitted?
Thank you.

**Comment by yosifkit** [comment] 2018-01-04 22:59
(assuming you are running Linux containers on Windows) You unfortunately cannot use a volume shared to the Windows host. See also, https://github.com/docker-library/mongo/issues/107#issuecomment-245690331.

> **WARNING (Windows & OS X)**: The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see [vbox bug](https://www.virtualbox.org/ticket/819), [docs.mongodb.org](https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories) and related [jira.mongodb.org](https://jira.mongodb.org/browse/SERVER-8600) bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.
>
> \- Docker Hub ([source](https://github.com/docker-library/docs/blob/b78d49c9dffe5dd8b3ffd1db338c62b9e1fc3db8/mongo/content.md#where-to-store-data))

Closing as duplicate of #107, #85, and #74.

**Closed by yosifkit** 2018-01-04 22:59 UTC

**Comment by tehmaestro** [comment] 2018-01-05 18:50
I'm using Docker on Windows with Hyper-V. Does it have the same issue?

**Comment by tianon** [comment] 2018-01-05 19:28
Very likely, yes.

**Comment by snehalsabale** [comment] 2020-05-16 17:28
I am getting below error on windows .
I have inastalled docker and node js. 
when I hit botfront up command getting below error.

PS C:\Chatbot\TestBotfront> botfront up
× Couldn't start Botfront. Retrying in verbose mode...
/ Starting Botfront...Creating network "testbotfront_botfront-network" with the default driver
- Starting Botfront...Creating volume "testbotfront_botfront-db" with default driver
Creating botfront-duckling ... done                                                                                                                                                          Creating botfront-mongo    ... done                                                                                                                                                          Creating botfront-rasa     ... done                                                                                                                                                          Creating botfront-actions  ... done                                                                                                                                                          Creating botfront-app      ... done                                                                                                                                                          Creating botfront-api      ... done                                                                                                                                                          × ERROR: Something went wrong. Check the logs above for more information ☝️, or try inspecting the logs with botfront logs.


In logs i have obseerved below messages:

botfront-api    | Connection to MongoDB server failed. Retrying... (#30)
botfront-api    | Connection to MongoDB server failed. Retrying... (#31)
botfront-api    | Connection to MongoDB server failed. Retrying... (#32).

Let me know how to resolve this.
