### ISSUE TITLE
MongoDB 4.2 is not suitable for use as a service in Gitlab CI

### ISSUE THREAD

**Issue by romintomasetti** [docker-library/mongo#390] opened 2020-02-28 16:59 UTC
# What's going on here?

Using the published Docker image of MongoDB (latest as of now, so 4.2.2 but I think the problem is the same with previous versions) as a service in Gitlab CI fails because the directory `/home/mongodb/` is missing.

```Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory```

# Proposed fix

See line https://github.com/docker-library/mongo/blob/fbaaf63e240b194cc3a05b859611c26b02035abf/4.2/Dockerfile#L4

Instead, it should be:

`RUN groupadd -r mongodb && useradd -r -m -g mongodb mongodb`

so that the home directory is created. Tested, it seemed to fix the issue.

**Comment by wglambert** [comment] 2020-02-28 17:32
Duplicate of https://github.com/docker-library/mongo/issues/323

**Comment by romintomasetti** [comment] 2020-02-28 18:56
@wglambert Indeed, just wanted to point the fix :smile:

**Closed** 2020-03-04 22:59 UTC
