### ISSUE TITLE
Disable Transparent Huge Pages (THP) as part of Dockerfile

### ISSUE THREAD

**Issue by kmluck** [docker-library/mongo#265] opened 2018-04-25 13:15 UTC
As per https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/:

> You should disable THP on Linux machines to ensure best performance with MongoDB.

However, the official docker image for MongoDB does not have THP disabled. I believe it would make sense to adjust the Dockerfile so that THP is disabled.

**Comment by tianon** [comment] 2018-04-25 17:06
Duplicate of https://github.com/docker-library/mongo/issues/112.

We cannot apply this change in the Docker image -- it has to be applied on your Docker host.

**Closed by tianon** 2018-04-25 17:06 UTC
