### ISSUE TITLE
v3.4.8 WiredTiger error (2) [1512186350:462630][1:0x7f6e98dc8d40], file:_mdb_catalog.wt, WT_SESSION.open_cursor: /data/db/_mdb_catalog.wt: handle-open: open: No such file or directory

### ISSUE THREAD

**Issue by leinue** [docker-library/mongo#218] opened 2017-12-02 03:50 UTC
user_db_1       | 2017-12-02T11:45:48.812+0800 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=5cb9c3f0c933
user_db_1       | 2017-12-02T11:45:48.812+0800 I CONTROL  [initandlisten] db version v3.4.8
user_db_1       | 2017-12-02T11:45:48.813+0800 I CONTROL  [initandlisten] git version: 8ef456f89f63ab12941fe6b5352b20cff2522da3
user_db_1       | 2017-12-02T11:45:48.813+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
user_db_1       | 2017-12-02T11:45:48.813+0800 I CONTROL  [initandlisten] allocator: tcmalloc
user_db_1       | 2017-12-02T11:45:48.814+0800 I CONTROL  [initandlisten] modules: none
user_db_1       | 2017-12-02T11:45:48.814+0800 I CONTROL  [initandlisten] build environment:
user_db_1       | 2017-12-02T11:45:48.815+0800 I CONTROL  [initandlisten]     distmod: debian81
user_db_1       | 2017-12-02T11:45:48.815+0800 I CONTROL  [initandlisten]     distarch: x86_64
user_db_1       | 2017-12-02T11:45:48.815+0800 I CONTROL  [initandlisten]     target_arch: x86_64
user_db_1       | 2017-12-02T11:45:48.816+0800 I CONTROL  [initandlisten] options: {}
user_db_1       | 2017-12-02T11:45:48.830+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
user_db_1       | 2017-12-02T11:45:50.462+0800 E STORAGE  [initandlisten] WiredTiger error (2) [1512186350:462630][1:0x7f6e98dc8d40], file:_mdb_catalog.wt, WT_SESSION.open_cursor: /data/db/_mdb_catalog.wt: handle-open: open: No such file or directory
user_db_1       | 2017-12-02T11:45:50.463+0800 E STORAGE  [initandlisten] no cursor for uri: table:_mdb_catalog
user_db_1       | 2017-12-02T11:45:50.464+0800 F -        [initandlisten] Invalid access at address: 0x58
user_db_1       | 2017-12-02T11:45:50.484+0800 F -        [initandlisten] Got signal: 11 (Segmentation fault).

**Comment by yosifkit** [comment] 2017-12-04 22:26
closing as duplicate of #219.

**Closed by yosifkit** 2017-12-04 22:26 UTC
