### ISSUE TITLE
why container mongo client can  connect mongod without --authenticationDatabase ? 

### ISSUE THREAD

**Issue by kulong0105** [docker-library/mongo#366] opened 2019-09-19 11:59 UTC
Question:
why **container mongo client** can connect mongod without authenticationDatabase ? 

The reproduce steps:

- start mongod service in machine-1:
```
[root@machine-1 ~]# docker run -p 27017:27017 -d -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo
1ba2e5875887c9e7954dadb6a9b162bd78238afba2a7a05a4d12ee62b27e9bd1
[root@machine-1 ~] hostname -I
192.168.50.121 172.17.0.1
[root@machine-1 ~]
```
- use **container mongo client** connect  machine-1's mongod in machine-2:
```
[root@machine-2 ~]#docker run -ti mongo  mongo --host  192.168.50.121 -u admin -p secret
MongoDB shell version v4.2.0
connecting to: mongodb://192.168.50.121:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("45470bd5-5bf0-4e95-a5af-ca2db26d7576") }
MongoDB server version: 4.2.0
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2019-09-19T11:46:06.832+0000 I  STORAGE  [main] In File::open(), ::open for '/home/mongodb/.mongorc.js' failed with No such file or directory
Server has startup warnings:
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
>
```
it works

- use **host mongo client** connect  machine-1's mongod in machine-2:
```
[root@machine-2 ~]# ./mongo --host  192.168.50.121 -u admin -p secret
MongoDB shell version v4.0.2-2-gddce0aa9fc
connecting to: mongodb://192.168.50.121:27017/
MongoDB server version: 4.2.0
WARNING: shell and server versions do not match
2019-09-19T19:47:47.478+0800 E QUERY    [js] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1685:20
@(auth):6:1
@(auth):1:2
exception: login failed
[root@machine-2 ~]# ./mongo --host  192.168.50.121 -u admin -p secret  --authenticationDatabase admin
MongoDB shell version v4.0.2-2-gddce0aa9fc
connecting to: mongodb://192.168.50.121:27017/
MongoDB server version: 4.2.0
WARNING: shell and server versions do not match
Server has startup warnings:
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-09-19T11:38:08.292+0000 I  CONTROL  [initandlisten]
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
>
```
it works only with `--authenticationDatabase admin` option

**Comment by wglambert** [comment] 2019-09-19 17:38
From what I can tell `mongo` will by default use `--authenticationDatabase admin`, you can test that by explicitly specifying a different one and it should fail.

Your non-containerized mongo client doesn't appear to be using the implicit default options. 
Also shown by the different connection url's: 
`connecting to: mongodb://192.168.50.121:27017/` compared to 
`connecting to: mongodb://192.168.50.121:27017/?compressors=disabled&gssapiServiceName=mongodb`

Using the host's mongo client these implicit options are passed
```console
$ docker run -p 27017:27017 -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo
0d3b45a626a7fd57b953e768071109003645ef54a5404043ef740f01b5c48661

$ sudo netstat -tulpn | grep 27017
tcp6       0      0 :::27017                :::*                    LISTEN      27010/docker-proxy

$ mongo --host localhost -u admin -p secret
MongoDB shell version v4.2.0                                                                                                                      
connecting to: mongodb://localhost:27017/?compressors=disabled&gssapiServiceName=mongodb                                                          
Implicit session: session { "id" : UUID("9513d30f-a091-45a0-bc74-edd814d1ff09") }                                                                 
MongoDB server version: 4.2.0                                                                                                                     
Server has startup warnings:                                                                                                                      
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten]                                                                                          
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine                                                                                                                                            
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem                      
---                                                                                                                                               
Enable MongoDB's free cloud-based monitoring service, which will then receive and display                                                         
metrics about your deployment (disk utilization, CPU, operation statistics, etc).                                                                 
                                                                                                                                                  
The monitoring data will be available on a MongoDB website with a unique URL accessible to you                                                    
and anyone you share the URL with. MongoDB may use this information to make product                                                               
improvements and to suggest MongoDB products and deployment options to you.                                                                       
                                                                                                                                                  
To enable free monitoring, run the following command: db.enableFreeMonitoring()                                                                   
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()                                                       
---

> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
> exit
bye

$ mongo --host localhost -u admin -p secret --authenticationDatabase local
MongoDB shell version v4.2.0                                                                                                                      
connecting to: mongodb://localhost:27017/?authSource=local&compressors=disabled&gssapiServiceName=mongodb                                         
2019-09-19T10:36:46.866-0700 E  QUERY    [js] Error: Authentication failed. :                                                                     
connect@src/mongo/shell/mongo.js:341:17                                                                                                           
@(connect):2:6                                                                                                                                    
2019-09-19T10:36:46.885-0700 F  -        [main] exception: connect failed                                                                         
2019-09-19T10:36:46.885-0700 E  -        [main] exiting with code 1

$ mongo --host localhost -u admin -p secret --authenticationDatabase config
MongoDB shell version v4.2.0                                                                                                                      
connecting to: mongodb://localhost:27017/?authSource=config&compressors=disabled&gssapiServiceName=mongodb                                        
2019-09-19T10:36:50.942-0700 E  QUERY    [js] Error: Authentication failed. :                                                                     
connect@src/mongo/shell/mongo.js:341:17                                                                                                           
@(connect):2:6                                                                                                                                    
2019-09-19T10:36:50.943-0700 F  -        [main] exception: connect failed                                                                         
2019-09-19T10:36:50.943-0700 E  -        [main] exiting with code 1

$ mongo --host localhost -u admin -p secret --authenticationDatabase admin
MongoDB shell version v4.2.0                                                                                                                      
connecting to: mongodb://localhost:27017/?authSource=admin&compressors=disabled&gssapiServiceName=mongodb                                         
Implicit session: session { "id" : UUID("7137d0b1-7382-44be-8979-a1151d0a8297") }                                                                 
MongoDB server version: 4.2.0
Server has startup warnings: 
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten] 
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-09-19T17:34:07.090+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

>
```

```console
$ mongo --version
MongoDB shell version v4.2.0
git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

$ docker exec mongodb mongo --version
MongoDB shell version v4.2.0
git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

**Comment by wglambert** [comment] 2019-09-19 21:27
Looks like the implicit auth db is from https://github.com/mongodb/mongo/blob/872a46afa66260b8ea59772aa20acb374939eef5/src/mongo/client/mongo_uri.h#L192-L201

```C
    std::string getAuthenticationDatabase() const {
        auto authDB = _options.find("authSource");
        if (authDB != _options.end()) {
            return authDB->second;
        } else if (!_database.empty()) {
            return _database;
        } else {
            return "admin";
        }
    }
```

**Comment by yosifkit** [comment] 2019-09-19 22:01
Following @wglambert's link to upstream's commit, the ticket in question was https://jira.mongodb.org/browse/SERVER-35212. So if your local mongo client less than 3.6.10, then it is probable that this is the cause.

Closing as it does not seem to be a problem in the Docker image.

**Closed by yosifkit** 2019-09-19 22:01 UTC
Labels: question

**Comment by kulong0105** [comment] 2019-09-20 03:49
@wglambert  
thanks,  upgrade mongo to 4.2.0, now it works!
